import ClientRootLayout from "./layout.client";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CombinedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientRootLayout>
          <ChakraProvider>{children}</ChakraProvider>
        </ClientRootLayout>
      </body>
    </html>
  );
}

// src/app/layout.server.tsx
